---
- name: Install Node
  ansible.builtin.package:
    name:
      - nodejs
    state: latest
  become: yes

- name: Install NPM
  ansible.builtin.package:
    name:
      - npm
    state: latest
  become: yes

- name: n install
  shell: npm install -g n
  become: yes