- name: default packages
  ansible.builtin.package:
    name:
      - apt-transport-https
      - curl
      - ca-certificates
      - mtr-tiny
      - nano
      - wget
    state: latest
  become: yes
