- name: tempfile
  ansible.builtin.tempfile: 
    prefix: .fetched_
    state: file
  register: tempfile

- name: get os-release
  ansible.builtin.fetch:
    src: /etc/os-release
    dest: "{{ tempfile.path }}"
    flat: yes
  register: fetched

- name: set version_id
  ansible.builtin.set_fact:
    version_id: "{{ lookup('ini', 'VERSION_ID type=properties file=' + fetched.dest) }}"

- name: add repository key
  vars:
    regex: "[`'\"]"
    replace: ""
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{version_id|regex_replace(regex, replace)}}/Release.key
    state: present
  become: yes

- name: add repository
  vars:
    regex: "[`'\"]"
    replace: ""
  ansible.builtin.apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{version_id|regex_replace(regex, replace)}}/ /
    filename: podman
    state: present
    update_cache: true
  become: yes

- name: Install
  ansible.builtin.apt:
    name: podman
    state: latest
  become: yes