- name: tempfile
  ansible.builtin.tempfile: 
    prefix: .fetched_
    state: file
  register: tempfile

- name: get os-release
  ansible.builtin.fetch:
    src: /etc/os-release
    dest: "{{ tempfile.path }}"
    flat: yes
  register: fetched

- name: set version_id
  ansible.builtin.set_fact:
    version_id: "{{ lookup('ini', 'VERSION_ID type=properties file=' + fetched_dest) }}"

- name: add repository
  ansible.builtin.apt_repository:
    repo: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{version_id}}/ /
    state: present
  become: yes

- name: add repository key
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{version_id}}/Release.key
    state: present

- name: Install
  ansible.builtin.apt:
    name: podman
    state: latest
    update_cache: true