- name: dependency install
  ansible.builtin.package:
    name:
      - curl
    state: latest
  become: yes

- name: download kubectl
  shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  become: yes

- name: download kubectl.sha256
  shell: curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
  become: yes

- name: validate
  shell: echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
  become: yes

- name: move to bin
  shell: cp kubectl /usr/local/bin/
  become: yes

- name: +x
  shell: chmod +x /usr/local/bin/kubectl
  become: yes

- name: cleanup kubectl.sha256
  shell: rm -rf kubectl.sha256
  become: yes

- name: cleanup kubectl
  shell: rm -rf kubectl
  become: yes